In [39]:
import numpy as np
list_ = np.random.randint(20, size=20)
in_list = list_
list_

array([ 2,  2,  8, 15,  7, 11,  4, 14,  1,  0,  8, 13, 11,  2, 10, 11,  8,
        6,  7, 11])

In [40]:
# 冒泡排序
def BubbleSore(in_list):
    if len(in_list)<2:
        return in_list
    else:
        for i in range(len(in_list)-1):
            for j in range(len(in_list)-1-i):
                if in_list[j] > in_list[j+1]:
                    max_ = in_list[j]
                    in_list[j], in_list[j+1] = in_list[j+1], max_
            print(in_list)
    return in_list

In [41]:
BubbleSore(in_list)

[ 2  2  8  7 11  4 14  1  0  8 13 11  2 10 11  8  6  7 11 15]
[ 2  2  7  8  4 11  1  0  8 13 11  2 10 11  8  6  7 11 14 15]
[ 2  2  7  4  8  1  0  8 11 11  2 10 11  8  6  7 11 13 14 15]
[ 2  2  4  7  1  0  8  8 11  2 10 11  8  6  7 11 11 13 14 15]
[ 2  2  4  1  0  7  8  8  2 10 11  8  6  7 11 11 11 13 14 15]
[ 2  2  1  0  4  7  8  2  8 10  8  6  7 11 11 11 11 13 14 15]
[ 2  1  0  2  4  7  2  8  8  8  6  7 10 11 11 11 11 13 14 15]
[ 1  0  2  2  4  2  7  8  8  6  7  8 10 11 11 11 11 13 14 15]
[ 0  1  2  2  2  4  7  8  6  7  8  8 10 11 11 11 11 13 14 15]
[ 0  1  2  2  2  4  7  6  7  8  8  8 10 11 11 11 11 13 14 15]
[ 0  1  2  2  2  4  6  7  7  8  8  8 10 11 11 11 11 13 14 15]
[ 0  1  2  2  2  4  6  7  7  8  8  8 10 11 11 11 11 13 14 15]
[ 0  1  2  2  2  4  6  7  7  8  8  8 10 11 11 11 11 13 14 15]
[ 0  1  2  2  2  4  6  7  7  8  8  8 10 11 11 11 11 13 14 15]
[ 0  1  2  2  2  4  6  7  7  8  8  8 10 11 11 11 11 13 14 15]
[ 0  1  2  2  2  4  6  7  7  8  8  8 10 11 11 11 11 13 14 15]
[ 0  1  

array([ 0,  1,  2,  2,  2,  4,  6,  7,  7,  8,  8,  8, 10, 11, 11, 11, 11,
       13, 14, 15])